// Generates a tiny blurred WebP placeholder for the map and writes it into lib/map.ts as MAP_BLUR.
// Usage: npm run placeholder
import { readFile, writeFile } from "node:fs/promises"
import { fileURLToPath } from "node:url"
import sharp from "sharp"

const svgPath = fileURLToPath(new URL("../public/maps/protheka.min.svg", import.meta.url))
const mapTsPath = fileURLToPath(new URL("../lib/map.ts", import.meta.url))

const webp = await sharp(await readFile(svgPath)).resize(40).webp({ quality: 50 }).toBuffer()
const dataUri = `data:image/webp;base64,${webp.toString("base64")}`

const src = await readFile(mapTsPath, "utf8")
const line = `export const MAP_BLUR = "${dataUri}"`
const re = /^export const MAP_BLUR = ".*"$/m
const out = re.test(src) ? src.replace(re, line) : src.replace(/^(export const MAP = .*)$/m, `$1\n\n// generated by scripts/placeholder.mjs — do not edit by hand\n${line}`)

await writeFile(mapTsPath, out)
console.log(`MAP_BLUR: ${webp.length} bytes webp, ${dataUri.length} chars data URI`)
