export const MAP = { w: 903, h: 672.75, minScale: 1, maxScale: 6 }

// generated by scripts/placeholder.mjs — do not edit by hand
export const MAP_BLUR = "data:image/webp;base64,UklGRgQFAABXRUJQVlA4WAoAAAAQAAAAJwAAHQAAQUxQSI0DAAABoGBbe9pI2v8WhhNb+v9fLBlih7ko2CmmZmbm0TYiIhRnKeONlHPeaAQtbIb/paQzAsWSpJkkrNH8N0m5WgRtJz3K626QtqWLwqyL0pZuszNVuxtCf0sEF0qsfDfMu760etwJMh/JQmplB1r5nn7pDYadAVgq5yXHfKTbhQ9GtyxgEHkXMD+86hb7+1zaVqAi18JPgkYYdfvj4bSd90acpbPdkphVuRSpNFzNpSCJ76yFAdcS56t1rXM7IuSjgxFUJBwjojTsMOUcfmog65CL7MXZpt73gaH/2JkiHcgUjcxTe+YFCX716sYKIitlqz+vTe2F7pYHxqiQu3QFHOFcglJ8FR9xAJ0ToMuGZpfLYPo/yrNpdmcrTgE4JMCcgkfhkaiPijSQ7qixEgutuKi/6h51/E4SCrRJQhL3ea9b18wQDadz3SrqCgLevZxg22DBGU+ajKWo8VfVjRGICLLPFwA4Js9EUVxt7n/4UpBuDxkDhop/rLexTYijuRdcag1W+BfjbIYgcJrDrH4OXW8NCPr0nghwvsiFa48qYKi05cLA9FZdikVJ2WBUK1WhWahhqCbCI1oGri/UABR6G3pCcnO1cbY6UZICzorHn77GJ5solRji0PT3lZvVigk88P5aSPnkuxKcy8BPZkdfY3y8GS891VlPM1NIORCw2s+MaxUYJAwCSnw7Ll/vHV0fnQ99rzj/pQ1qf1yn8DwXjhBJSf767p2z3/H2Wdb69GwxWMxasj13gJoyzysUoN4sT3OnYVuLD1P9cVz7Qe90Ni7R9h5KkKe7SfAG67HNYjysBZDQTsjtyffHo/7q4WEJcPY/Kv0qxp+ZWxvKdH613ijeCoUQclIpELLMMgVo3vCC7scYx2Kt4pmevZEvpawUh9zxJOty49qFFlre3/ru7xjjltTNt3dx8EG/NDRS2RZQEFoDM62z/qwzORph9XlSusq6o+qku1sqLTaiagVtLFiJdWzXXn+P0SxAdZ0kG1y2lXn1Wui+Qux18w5R5uSJQ6AyLuZ1yApw8lk57qB52TkkNZEKpliMxWW77IwSRgnF/sH571+yw8fd+fRgeVsaKTAjjUExHErhnp0WKTPZe0XFDyIJt6eb+y+rjLCUWtxvOV9/+hg3h59j7FRafxl3q4qUZDkbP5arlv54zRk1mo0kafyXpmnabDb++++Pxl8pNJoN4I2UN5sMUDWa/3IAVlA4IFABAAAQCACdASooAB4APsVUpUunpKQhsAqo8BiJZwDQ0bXxp9qMsvS0NIC9j7c1QiCDBi7nGF6xOiKF4aEsdpmTezVdISXMnGC5l+cAAP5ly1dENCQWLYDNTcJGmNnezBRDMD/GPnwzgLjz94ULWqABDFsJ5c5bdjL4wmknROx7gOsEFKW4mbbg7blvW72g5qgJkSa3cDkBHniXysIMbZFnwzD4Vep/14qfrXSEScxR9wkkblhx7yWy9R6iWikOENYQAL+oPKKitA/dRR0HF6fz3aa3eJxKAcGSgqzdT2NuBKWAMXcjtTNeCe+IqbKTTidXNbl4T2pOE55fjbSnWsFWjjRiQ88XCcGKyBs/l4YSO6lHVrfV45nYnomZn278XIfSEwtfa+lJ9fIJVAUirT3vtIUS9vgCXCyKrfefK1nS9Wm8ryc8wo7VoLpb6eiNvLdAAAA="

// zoom thresholds for "level of detail"
export const LVL2 = 1.8
export const LVL3 = 3.2

// atmosphere tunables (textures: npm run atmos -> public/maps/atmos/)
export const ATMOS = {
  paperOpacity: 0.4,    // paper grain, multiplied over the map
  paperTile: 256,       // css px per paper tile at 1x zoom
  edgeBurn: 0.85,       // alpha of the burnt edge (fades into the page background)
  edgeSize: 7,          // burnt edge width, % of the map
  vignette: 0.5,        // screen-space vignette darkness
  light: 0.16,          // screen-space warm candle glow from the top-left (static; the vignette flickers)
  cloudOpacity: 0.75,   // clouds at 1x zoom (they hug the frame, clear of names/banners)
  cloudFadeStart: 1,    // clouds start fading at this scale...
  cloudFadeEnd: 2,      // ...and are gone (and hidden) from this scale
  parallax: 1.15,       // clouds pan this much faster than the map (closer to the camera)
  cloudPush: 0.6,       // extra outward spread/growth of clouds by the end of the fade
  shadowOpacity: 0.18,  // drifting cloud shadows on the ground
  driftSeconds: [70, 95, 120], // one full back-and-forth loop per shadow
} as const

// "arrive through the clouds" intro: once per session (sessionStorage "protheka-intro-seen"),
// skipped under prefers-reduced-motion, ?atmos=0 and ?poi= deep links. Any input skips it.
export const INTRO = {
  holdMs: 400,          // dense clouds hold after the map has faded in
  durationMs: 2500,     // clouds part, veil lifts, camera settles
  targetPoi: "capital", // POI id the camera ends centred on (clamped to the map bounds)
  targetScale: 1.2,
  dim: 0.4,             // dark veil over the map at the start
} as const

// depth tilt (Tilt.tsx): the screen-space clouds and candle glow shift against the map with device
// tilt (phones) or the mouse (desktop). Off under prefers-reduced-motion and with ?atmos=0.
export const TILT = {
  cloudRange: 14,       // px: clouds (closest to the camera) shift up to this far
  lightRange: 8,        // px: the candle glow shifts the opposite way (the light source stays put);
                        //     keep <= the 16px padding of .atmos-tilt-pad in globals.css
  smoothing: 180,       // ms: low-pass time constant (higher = floatier)
  recenterSpeed: 4,     // s: the phone's neutral re-centres on how it's being held over about this long
  maxTiltDeg: 20,       // phone tilt away from neutral that reaches the full range
} as const

// ambient life after the intro. All of it pauses while the user moves and while the tab is hidden,
// is off under prefers-reduced-motion (smoke shows one still wisp) and with ?atmos=0.
export const AMBIENT = {
  volcano: { x: 46, y: 62.8 },  // % of map: smoke source = top of the drawn plume above "Kalyunbar"
  smoke: {
    count: 6,                   // wisps (textures wisp-1..6), staggered
    durationS: [6, 10],         // each wisp's loop, spread across this range
    opacity: 0.8,               // peak opacity of the smoke
    width: 4.5,                 // wisp width, % of map width (box is 2:3)
  },
  birds: {
    everyS: [13, 17],           // start-to-start between departures, ~15s (set [15, 15] for exact)
    count: [3, 5],              // birds per flock (randomized); each departure = 2 flocks crossing paths
    flightS: [11, 15],          // time for a flock to cross the map (randomized)
    maxFlocks: 4,               // cap, so departures can't pile up while the animations are paused
  },
  flicker: 0.35,                // candle flicker: the vignette's shadows ease back by up to ~35% as the flame flares
} as const

export type POIKind = "region" | "city" | "landmark"

export type POI = {
  id: string
  name: string
  kind: POIKind
  blurb: string          // one line, shown in the sheet's peek state
  lore: string           // short paragraph
  chapters: string[]     // chapter titles set here
  characters?: string[]
  x: number              // % from left of map
  y: number              // % from top
  minLevel: 1 | 2 | 3    // zoom level at which the pin appears (LVL2 / LVL3)
  storyId: string
}

// placeholder content until the real lore is written
export const POIS: POI[] = [
  {
    id: "capital",
    name: "Aldhollow",
    kind: "city",
    blurb: "Seat of the old crown.",
    lore:
      "Aldhollow was raised inside the husk of a fallen mountain, its streets cut in rings around an empty throne. " +
      "The crown has been missing for forty winters, and the Council of Thirteen rules in its name, arguing over " +
      "whose turn it is to sit beside the chair nobody sits in.",
    chapters: ["The Empty Throne", "Ashes in the Lower Ring", "A Council of Thirteen"],
    characters: ["Maren Vell, keeper of the throne room", "Old Tobin, the lamplighter", "Captain Idris Hale"],
    x: 42,
    y: 37,
    minLevel: 1,
    storyId: "ch1",
  },
  {
    id: "pass",
    name: "Greyfang Pass",
    kind: "landmark",
    blurb: "Where the caravan vanished.",
    lore:
      "The only road north runs between two broken peaks the shepherds call the Fangs. Last autumn a salt caravan of " +
      "thirty wagons went up into the fog and never came down the other side. The snow has kept the wheel ruts, " +
      "and they stop in the middle of the road.",
    chapters: ["Tracks in the Snow", "The Thirty Wagons"],
    characters: ["Sella of the Salt Road", "The guide with no name"],
    x: 61,
    y: 22,
    minLevel: 2,
    storyId: "ch2",
  },
  {
    id: "well",
    name: "Hollow Well",
    kind: "landmark",
    blurb: "Something hums below.",
    lore:
      "An old stone well at the edge of a village that no longer exists. Drop a pebble and you never hear it land. " +
      "On still nights the well hums a single low note, and the dogs of the nearby farms refuse to sleep.",
    chapters: ["The Humming", "What the Rope Brought Up"],
    x: 30,
    y: 64,
    minLevel: 3,
    storyId: "ch3",
  },
]

// focus mode: what happens when a location is opened
export const FOCUS = {
  zoom: { region: 1.8, city: 3, landmark: 4 } as Record<POIKind, number>, // target scale per kind (never zooms out)
  flyMs: 900,             // camera flight to a location
  spotlight: 0.45,        // darkness around the focused location
  spotlightRadius: 0.22,  // clear area around it, x the smaller viewport side
}

// location sheet (phones) / side panel (desktop); camera framing uses these too
export const SHEET = {
  peekPx: 148,            // peek height: name + kind + one line
  half: 0.5,              // half snap, fraction of the viewport height (the camera frames above it)
  full: 0.92,             // full snap
  panelPx: 380,           // desktop side panel width
  desktopQuery: "(min-width: 1024px) and (pointer: fine)",
} as const